
###Get all the rows from the database in this table
POST http://localhost:7318/Custom/Cleaning/Factory/V1/Inward/Return/QrCode/Vizag
Content-Type: application/json

{
    "QrCodeId": "10",
    "ItemName": "shirt",
    "Rate": "90",
    "FactorySelected": "Vizag",
    "VoucherRef": "1",
    "BranchName": "KKD",
    "VoucherNumber": "1",
    "DCFactory": "undefined",
    "DCDate": "2024-12-05",
    "DCDescription": "return",
    "OrderNumber": "1",
    "OrderDate": "2024-12-05 11:29:50",
    "DeliveryDate": "2024-12-12",
    "Description": "return",
    "FactoryName": "Vizag"
}