### Qr Raise
POST  http://localhost:7318/Custom/Cleaning/Branch/Order/NewOrder/ANR
Content-Type: application/json

{
    "ItemsInOrder": {},
    "CustomerData": {
        "CustomerName": "Keshav",
        "CustomerMobile": "9848163021"
    },
    "OrderData": {
        "BranchName": "ANR",
        "Currentdateandtime": "2024-09-24 14:27:35"
    },
    "AddOnData": {},
    "CheckOutData": {}
}